server:
  port: 8083
spring:

#local database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/vnpay_db
    username: postgres
    password: postgres
    hikari:
      schema: vnpay_db_vnpt



