server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/vnpay_db
    username: postgres
    password: chiendao18082001
    hikari:
      schema: vnpay_db_vnpt

